import { FrameworkEvent } from "../Standard/Events";
export declare class DragDropHandler {
    constructor(target: any);
    private __onTouchStart;
    private __onTouchMove;
    private __onTouchEnd;
    private __onTouchCancel;
    private __target_onMouseDown;
    private __window_onMouseUp;
    private __window_onMouseMove;
    private __touchDragDelayTimer_onTick;
    private __doRequestDragStart;
    private __doDragStart;
    private __doDragMove;
    private __doDragEnd;
    private __doDragCancel;
    private __doDragEnter;
    private __doDragOver;
    private __doDragLeave;
    private __doDragDrop;
    private __onNotifyDragMove;
    private __onNotifyDragEnd;
    private __NotifyDragStartEvent;
    private __NotifyDragMoveEvent;
    private __NotifyDragEndEvent;
    private __NotifyDragCancelEvent;
    private __RequestDragStartEvent;
    private __DragStartEvent;
    private __DragMoveEvent;
    private __DragEndEvent;
    private __DragCancelEvent;
    private __DragEnterEvent;
    private __DragOverEvent;
    private __DragLeaveEvent;
    private __DragDropEvent;
    private __emulator;
    private __data;
    private __context;
    private __acceptsDrag;
    private __acceptsDrop;
    private __state;
    private __touchDragDelayTimer;
    readonly RequestDragStartEvent: FrameworkEvent;
    readonly DragStartEvent: FrameworkEvent;
    readonly DragMoveEvent: FrameworkEvent;
    readonly DragEndEvent: FrameworkEvent;
    readonly DragCancelEvent: FrameworkEvent;
    readonly DragEnterEvent: FrameworkEvent;
    readonly DragOverEvent: FrameworkEvent;
    readonly DragLeaveEvent: FrameworkEvent;
    readonly DragDropEvent: FrameworkEvent;
    readonly target: Element;
    private __target;
}
