import { FrameworkProperty } from "./user-interface";
import { FrameworkEvent, NativeEvent } from "../Standard/Events";
export declare abstract class Widget {
    constructor(namespaceURI: any, qualifiedName: any);
    private __dragDropHandler;
    protected connectedCallback(): void;
    protected disconnectedCallback(): void;
    private __dragDropHandler__onRequestDragStart;
    private __dragDropHandler__onDragStart;
    private __dragDropHandler__onDragMove;
    private __dragDropHandler__onDragEnd;
    private __dragDropHandler__onDragCancel;
    private __dragDropHandler__onDragEnter;
    private __dragDropHandler__onDragOver;
    private __dragDropHandler__onDragLeave;
    private __dragDropHandler__onDragDrop;
    private __onDragMove;
    DragStartEvent: FrameworkEvent;
    private __onDragStart;
    DragMoveEvent: FrameworkEvent;
    private __onDragEnd;
    DragEndEvent: FrameworkEvent;
    private __onDragCancel;
    DragCancelEvent: FrameworkEvent;
    private __onDragEnter;
    DragEnterEvent: FrameworkEvent;
    private __onDragOver;
    DragOverEvent: FrameworkEvent;
    private __onDragLeave;
    DragLeaveEvent: FrameworkEvent;
    private __onDragDrop;
    DragDropEvent: FrameworkEvent;
    private __onMouseEnter;
    MouseEnterEvent: NativeEvent;
    private __onMouseLeave;
    MouseLeaveEvent: NativeEvent;
    private __onMouseDown;
    MouseDownEvent: NativeEvent;
    private __onMouseMove;
    MouseMoveEvent: NativeEvent;
    private __onMouseUp;
    MouseUpEvent: NativeEvent;
    private __onClick;
    ClickEvent: NativeEvent;
    static isMouseOverProperty: FrameworkProperty;
    get isMouseOver(): any;
    set isMouseOver(value: any);
    static isDraggingProperty: FrameworkProperty;
    get isDragging(): any;
    set isDragging(value: any);
    static isDragOverProperty: FrameworkProperty;
    get isDragOver(): any;
    set isDragOver(value: any);
    static isDraggableProperty: FrameworkProperty;
    get isDraggable(): any;
    set isDraggable(value: any);
}
