const NS = "http://www.w3.org/2000/svg";

export const SVG_ELEMENT_DATA_MAP = {
    //Extracted from https://svgwg.org/svg2-draft/struct.html#SVGElement
    //$$("a").map(a => a.href.match(/(\w+)Element/)).filter(m => m).map(m => m[1].replace(/^[A-Z]+/, s => s.toLowerCase())).sort((n, o) => n > o ? 1 : -1).map(n => `["${n}", NS, "${document.createElementNS("http://www.w3.org/2000/svg", n).constructor.name}"]`).join(", ")
    "a": { namespaceUri: NS, ctorName: "SVGAElement" },
    "animate": { namespaceUri: NS, ctorName: "SVGAnimateElement" },
    "animateMotion": { namespaceUri: NS, ctorName: "SVGAnimateMotionElement" },
    "animateTransform": { namespaceUri: NS, ctorName: "SVGAnimateTransformElement" },
    "circle": { namespaceUri: NS, ctorName: "SVGCircleElement" },
    "clipPath": { namespaceUri: NS, ctorName: "SVGClipPathElement" },
    "defs": { namespaceUri: NS, ctorName: "SVGDefsElement" },
    "desc": { namespaceUri: NS, ctorName: "SVGDescElement" },
    "ellipse": { namespaceUri: NS, ctorName: "SVGEllipseElement" },
    "feBlend": { namespaceUri: NS, ctorName: "SVGFEBlendElement" },
    "feColorMatrix": { namespaceUri: NS, ctorName: "SVGFEColorMatrixElement" },
    "feComponentTransfer": { namespaceUri: NS, ctorName: "SVGFEComponentTransferElement" },
    "feComposite": { namespaceUri: NS, ctorName: "SVGFECompositeElement" },
    "feConvolveMatrix": { namespaceUri: NS, ctorName: "SVGFEConvolveMatrixElement" },
    "feDiffuseLighting": { namespaceUri: NS, ctorName: "SVGFEDiffuseLightingElement" },
    "feDisplacementMap": { namespaceUri: NS, ctorName: "SVGFEDisplacementMapElement" },
    "feDistantLight": { namespaceUri: NS, ctorName: "SVGFEDistantLightElement" },
    "feDropShadow": { namespaceUri: NS, ctorName: "SVGFEDropShadowElement" },
    "feFlood": { namespaceUri: NS, ctorName: "SVGFEFloodElement" },
    "feFuncA": { namespaceUri: NS, ctorName: "SVGFEFuncAElement" },
    "feFuncB": { namespaceUri: NS, ctorName: "SVGFEFuncBElement" },
    "feFuncG": { namespaceUri: NS, ctorName: "SVGFEFuncGElement" },
    "feFuncR": { namespaceUri: NS, ctorName: "SVGFEFuncRElement" },
    "feGaussianBlur": { namespaceUri: NS, ctorName: "SVGFEGaussianBlurElement" },
    "feImage": { namespaceUri: NS, ctorName: "SVGFEImageElement" },
    "feMerge": { namespaceUri: NS, ctorName: "SVGFEMergeElement" },
    "feMorphology": { namespaceUri: NS, ctorName: "SVGFEMorphologyElement" },
    "feOffset": { namespaceUri: NS, ctorName: "SVGFEOffsetElement" },
    "fePointLight": { namespaceUri: NS, ctorName: "SVGFEPointLightElement" },
    "feSpecularLighting": { namespaceUri: NS, ctorName: "SVGFESpecularLightingElement" },
    "feSpotLight": { namespaceUri: NS, ctorName: "SVGFESpotLightElement" },
    "feTile": { namespaceUri: NS, ctorName: "SVGFETileElement" },
    "feTurbulence": { namespaceUri: NS, ctorName: "SVGFETurbulenceElement" },
    "filter": { namespaceUri: NS, ctorName: "SVGFilterElement" },
    "foreignObject": { namespaceUri: NS, ctorName: "SVGForeignObjectElement" },
    "g": { namespaceUri: NS, ctorName: "SVGGElement" },
    "image": { namespaceUri: NS, ctorName: "SVGImageElement" },
    "line": { namespaceUri: NS, ctorName: "SVGLineElement" },
    "linearGradient": { namespaceUri: NS, ctorName: "SVGLinearGradientElement" },
    "marker": { namespaceUri: NS, ctorName: "SVGMarkerElement" },
    "mask": { namespaceUri: NS, ctorName: "SVGMaskElement" },
    "metadata": { namespaceUri: NS, ctorName: "SVGMetadataElement" },
    "mpath": { namespaceUri: NS, ctorName: "SVGMPathElement" },
    "path": { namespaceUri: NS, ctorName: "SVGPathElement" },
    "pattern": { namespaceUri: NS, ctorName: "SVGPatternElement" },
    "polygon": { namespaceUri: NS, ctorName: "SVGPolygonElement" },
    "polyline": { namespaceUri: NS, ctorName: "SVGPolylineElement" },
    "radialGradient": { namespaceUri: NS, ctorName: "SVGRadialGradientElement" },
    "rect": { namespaceUri: NS, ctorName: "SVGRectElement" },
    "script": { namespaceUri: NS, ctorName: "SVGScriptElement" },
    "set": { namespaceUri: NS, ctorName: "SVGSetElement" },
    "stop": { namespaceUri: NS, ctorName: "SVGStopElement" },
    "style": { namespaceUri: NS, ctorName: "SVGStyleElement" },
    "svg": { namespaceUri: NS, ctorName: "SVGSVGElement" },
    "switch": { namespaceUri: NS, ctorName: "SVGSwitchElement" },
    "symbol": { namespaceUri: NS, ctorName: "SVGSymbolElement" },
    "text": { namespaceUri: NS, ctorName: "SVGTextElement" },
    "textPath": { namespaceUri: NS, ctorName: "SVGTextPathElement" },
    "title": { namespaceUri: NS, ctorName: "SVGTitleElement" },
    "use": { namespaceUri: NS, ctorName: "SVGUseElement" },
    "view": { namespaceUri: NS, ctorName: "SVGViewElement" },
} as const;