import { FrameworkProperty } from "../user-interface";
import { FrameworkEvent, NativeEvent } from "../../Standard/Events";
import { Destructible } from "../../Standard/Destructible";
export declare abstract class Widget extends Destructible {
    constructor(namespaceURI: any, qualifiedName: any);
    private __dragDropHandler;
    private __dragDropHandler__onRequestDragStart;
    private __dragDropHandler__onDragStart;
    private __dragDropHandler__onDragMove;
    private __dragDropHandler__onDragEnd;
    private __dragDropHandler__onDragCancel;
    private __dragDropHandler__onDragEnter;
    private __dragDropHandler__onDragOver;
    private __dragDropHandler__onDragLeave;
    private __dragDropHandler__onDragDrop;
    private __onDragMove;
    DragStartEvent: FrameworkEvent;
    private __onDragStart;
    DragMoveEvent: FrameworkEvent;
    private __onDragEnd;
    DragEndEvent: FrameworkEvent;
    private __onDragCancel;
    DragCancelEvent: FrameworkEvent;
    private __onDragEnter;
    DragEnterEvent: FrameworkEvent;
    private __onDragOver;
    DragOverEvent: FrameworkEvent;
    private __onDragLeave;
    DragLeaveEvent: FrameworkEvent;
    private __onDragDrop;
    DragDropEvent: FrameworkEvent;
    private __onMouseEnter;
    MouseEnterEvent: NativeEvent;
    private __onMouseLeave;
    MouseLeaveEvent: NativeEvent;
    private __onMouseDown;
    MouseDownEvent: NativeEvent;
    private __onMouseMove;
    MouseMoveEvent: NativeEvent;
    private __onMouseUp;
    MouseUpEvent: NativeEvent;
    private __onClick;
    ClickEvent: NativeEvent;
    static isMouseOverProperty: FrameworkProperty;
    isMouseOver: any;
    static isDraggingProperty: FrameworkProperty;
    isDragging: any;
    static isDragOverProperty: FrameworkProperty;
    isDragOver: any;
    static isDraggableProperty: FrameworkProperty;
    isDraggable: any;
}
